In [20]:
import pandas as pd

In [21]:
df=pd.read_csv('/content/covid_toy.csv')

In [22]:
df.sample(5)

    age  gender  fever   cough     city has_covid
92   82  Female  102.0  Strong  Kolkata        No
40   49  Female  102.0    Mild    Delhi        No
50   19    Male  101.0    Mild    Delhi       Yes
3    31  Female   98.0    Mild  Kolkata        No
30   15    Male  101.0    Mild    Delhi       Yes

In [23]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [25]:
X_train

    age  gender  fever   cough       city
67   65    Male   99.0    Mild  Bangalore
60   24  Female  102.0  Strong  Bangalore
43   22  Female   99.0    Mild  Bangalore
17   40  Female   98.0  Strong      Delhi
3    31  Female   98.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
87   47    Male  101.0  Strong  Bangalore
80   14  Female   99.0    Mild     Mumbai
51   11  Female  100.0  Strong    Kolkata
18   64  Female   98.0    Mild  Bangalore
70   68  Female  101.0  Strong      Delhi

[80 rows x 5 columns]

In [26]:
from sklearn.compose import ColumnTransformer

In [27]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

transformer = ColumnTransformer(transformers=[

    ('tnf1', SimpleImputer(strategy='most_frequent'), ['fever']),

    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),

    ('tnf3', OneHotEncoder(drop='first'), ['gender', 'city'])

], remainder='passthrough')

In [31]:
transformer.fit_transform(X_train).shape

(80, 7)