In [35]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

In [36]:
df=pd.read_json("../datasets/test.json")

In [37]:
df

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

In [38]:
pd.read_json('https://jsonplaceholder.typicode.com/posts')

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

In [41]:
import requests

url = "https://www.scrapethissite.com/pages/forms/?page_num=2&q=sa"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36",
}

res = requests.get(url, headers=headers)

print(res.status_code)        # 200
print(type(res))              # <class 'requests.models.Response'>
print(res.text)        # HTML content

200
<class 'requests.models.Response'>
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="hockey">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Hockey Teams: Forms, Searching and Pagination
                            <small>16 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">8 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://www.opensourcesports.com/hockey/" class="data-attribution" target="_blank">http://www.opensourcesports.com/hockey/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row search-area">
                    <div class="col-md-12 text-center">
                        <form method="GET" action="/pages/forms/" class="form form-inline">
                            <label for="q">
                                Search for Teams: &nbsp;
                            </label>
                            <input type="text" class="form-control" name="q" id="q" placeholder="Search for Teams" value="sa"/>

                            <input type="submit" class="btn btn-primary" value="Search" />
                        </form>
                        <hr>
                    </div>
                </div><!--.row.search-area-->


                <table class="table">
                    <tr>
                        <th>
                            Team Name
                        </th>
                        <th>
                            Year
                        </th>
                        <th>
                            Wins
                        </th>
                        <th>
                            Losses
                        </th>
                        <th>
                            OT Losses
                        </th>
                        <th>
                            Win %
                        </th>
                        <th>
                            Goals For (GF)
                        </th>
                        <th>
                            Goals Against (GA)
                        </th>
                        <th>
                            + / -
                        </th>
                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            2003
                        </td>
                        <td class="wins">
                            37
                        </td>
                        <td class="losses">
                            34
                        </td>
                        <td class="ot-losses">
                            4
                        </td>


                        <td class="pct text-danger">
                            0.451
                        </td>

                        <td class="gf">
                            220
                        </td>
                        <td class="ga">
                            221
                        </td>


                        <td class="diff text-danger">
                            -1
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            San Jose Sharks
                        </td>
                        <td class="year">
                            2003
                        </td>
                        <td class="wins">
                            43
                        </td>
                        <td class="losses">
                            21
                        </td>
                        <td class="ot-losses">
                            6
                        </td>


                        <td class="pct text-success">
                            0.524
                        </td>

                        <td class="gf">
                            219
                        </td>
                        <td class="ga">
                            183
                        </td>


                        <td class="diff text-success">
                            36
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            2005
                        </td>
                        <td class="wins">
                            52
                        </td>
                        <td class="losses">
                            24
                        </td>
                        <td class="ot-losses">
                            6
                        </td>


                        <td class="pct text-success">
                            0.634
                        </td>

                        <td class="gf">
                            281
                        </td>
                        <td class="ga">
                            239
                        </td>


                        <td class="diff text-success">
                            42
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            San Jose Sharks
                        </td>
                        <td class="year">
                            2005
                        </td>
                        <td class="wins">
                            44
                        </td>
                        <td class="losses">
                            27
                        </td>
                        <td class="ot-losses">
                            11
                        </td>


                        <td class="pct text-success">
                            0.537
                        </td>

                        <td class="gf">
                            266
                        </td>
                        <td class="ga">
                            242
                        </td>


                        <td class="diff text-success">
                            24
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            2006
                        </td>
                        <td class="wins">
                            53
                        </td>
                        <td class="losses">
                            22
                        </td>
                        <td class="ot-losses">
                            7
                        </td>


                        <td class="pct text-success">
                            0.646
                        </td>

                        <td class="gf">
                            308
                        </td>
                        <td class="ga">
                            242
                        </td>


                        <td class="diff text-success">
                            66
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            San Jose Sharks
                        </td>
                        <td class="year">
                            2006
                        </td>
                        <td class="wins">
                            51
                        </td>
                        <td class="losses">
                            26
                        </td>
                        <td class="ot-losses">
                            5
                        </td>


                        <td class="pct text-success">
                            0.622
                        </td>

                        <td class="gf">
                            258
                        </td>
                        <td class="ga">
                            199
                        </td>


                        <td class="diff text-success">
                            59
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            2007
                        </td>
                        <td class="wins">
                            39
                        </td>
                        <td class="losses">
                            31
                        </td>
                        <td class="ot-losses">
                            12
                        </td>


                        <td class="pct text-danger">
                            0.476
                        </td>

                        <td class="gf">
                            255
                        </td>
                        <td class="ga">
                            242
                        </td>


                        <td class="diff text-success">
                            13
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            San Jose Sharks
                        </td>
                        <td class="year">
                            2007
                        </td>
                        <td class="wins">
                            49
                        </td>
                        <td class="losses">
                            23
                        </td>
                        <td class="ot-losses">
                            10
                        </td>


                        <td class="pct text-success">
                            0.598
                        </td>

                        <td class="gf">
                            222
                        </td>
                        <td class="ga">
                            193
                        </td>


                        <td class="diff text-success">
                            29
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            2008
                        </td>
                        <td class="wins">
                            41
                        </td>
                        <td class="losses">
                            32
                        </td>
                        <td class="ot-losses">
                            9
                        </td>


                        <td class="pct text-success">
                            0.5
                        </td>

                        <td class="gf">
                            250
                        </td>
                        <td class="ga">
                            234
                        </td>


                        <td class="diff text-success">
                            16
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            San Jose Sharks
                        </td>
                        <td class="year">
                            2008
                        </td>
                        <td class="wins">
                            53
                        </td>
                        <td class="losses">
                            18
                        </td>
                        <td class="ot-losses">
                            11
                        </td>


                        <td class="pct text-success">
                            0.646
                        </td>

                        <td class="gf">
                            257
                        </td>
                        <td class="ga">
                            204
                        </td>


                        <td class="diff text-success">
                            53
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            2009
                        </td>
                        <td class="wins">
                            45
                        </td>
                        <td class="losses">
                            27
                        </td>
                        <td class="ot-losses">
                            10
                        </td>


                        <td class="pct text-success">
                            0.549
                        </td>

                        <td class="gf">
                            235
                        </td>
                        <td class="ga">
                            207
                        </td>


                        <td class="diff text-success">
                            28
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            San Jose Sharks
                        </td>
                        <td class="year">
                            2009
                        </td>
                        <td class="wins">
                            51
                        </td>
                        <td class="losses">
                            20
                        </td>
                        <td class="ot-losses">
                            11
                        </td>


                        <td class="pct text-success">
                            0.622
                        </td>

                        <td class="gf">
                            264
                        </td>
                        <td class="ga">
                            215
                        </td>


                        <td class="diff text-success">
                            49
                        </td>

                    </tr>

                    <tr class="team">
                        <td class="name">
                            Buffalo Sabres
                        </td>
                        <td class="year">
                            2010
                        </td>
                        <td class="wins">
                            43
                        </td>
                        <td class="losses">
                            29
                        </td>

In [42]:
soup=BeautifulSoup(res,'lxml')

FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?