##Dataset1

In [5]:
import pandas as pd

data = {
    "student": ["Aman", "Riya", "Kunal", "Neha", "Arjun"],
    "study_hours": ["Low", "Medium", "High", "Medium", "Low"],
    "parent_support": ["Poor", "Average", "Good", "Good", "Average"],
    "performance": ["Below Avg", "Average", "Excellent", "Good", "Average"]
}

df = pd.DataFrame(data)
df

  student study_hours parent_support performance
0    Aman         Low           Poor   Below Avg
1    Riya      Medium        Average     Average
2   Kunal        High           Good   Excellent
3    Neha      Medium           Good        Good
4   Arjun         Low        Average     Average

Step 1: Define order

In [6]:
from sklearn.preprocessing import OrdinalEncoder

study_order = ["Low", "Medium", "High"]
support_order = ["Poor", "Average", "Good"]
performance_order = ["Below Avg", "Average", "Good", "Excellent"]

Step 2: Encode

In [7]:
oe = OrdinalEncoder(
    categories=[study_order, support_order, performance_order]
)

df[["study_hours_ord",
    "parent_support_ord",
    "performance_ord"]] = oe.fit_transform(
    df[["study_hours", "parent_support", "performance"]]
)

df

,student,study_hours,parent_support,performance,study_hours_ord,parent_support_ord,performance_ord
0,Aman,Low,Poor,Below Avg,0.0,0.0,0.0
1,Riya,Medium,Average,Average,1.0,1.0,1.0
2,Kunal,High,Good,Excellent,2.0,2.0,3.0
3,Neha,Medium,Good,Good,1.0,2.0,2.0
4,Arjun,Low,Average,Average,0.0,1.0,1.0


##Dataset2

In [8]:


data = {
    "user": ["Rohit", "Ananya", "Suresh", "Meena", "Kabir"],
    "difficulty": ["Easy", "Medium", "Hard", "Medium", "Easy"],
    "content_quality": ["Poor", "Good", "Excellent", "Average", "Good"],
    "satisfaction": ["Low", "Medium", "High", "High", "Medium"]
}

df = pd.DataFrame(data)
df

     user difficulty content_quality satisfaction
0   Rohit       Easy            Poor          Low
1  Ananya     Medium            Good       Medium
2  Suresh       Hard       Excellent         High
3   Meena     Medium         Average         High
4   Kabir       Easy            Good       Medium

In [9]:
#Define order
diff_order=["Easy","Medium","Hard"]
quality_order=["Poor","Average","Good","Excellent"]
satisfaction_order=["Low","Medium","High"]

In [11]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[diff_order, quality_order, satisfaction_order]
)

df[[
    "difficulty_ord",
    "content_quality_ord",
    "satisfaction_ord"
]] = oe.fit_transform(
    df[["difficulty", "content_quality", "satisfaction"]]
)

df

,user,difficulty,content_quality,satisfaction,difficulty_ord,content_quality_ord,satisfaction_ord
0,Rohit,Easy,Poor,Low,0.0,0.0,0.0
1,Ananya,Medium,Good,Medium,1.0,2.0,1.0
2,Suresh,Hard,Excellent,High,2.0,3.0,2.0
3,Meena,Medium,Average,High,1.0,1.0,2.0
4,Kabir,Easy,Good,Medium,0.0,2.0,1.0

#Dataset 3 Label Encoder for catgorical output

In [13]:
import pandas as pd

data = {
    "user": ["Rohit", "Ananya", "Suresh", "Meena", "Kabir"],
    "course": ["Python", "Java", "Python", "C++", "Java"],
    "city": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}

df = pd.DataFrame(data)
df

     user  course    city
0   Rohit  Python   Delhi
1  Ananya    Java  Mumbai
2  Suresh  Python   Delhi
3   Meena     C++    Pune
4   Kabir    Java  Mumbai

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["course_le"] = le.fit_transform(df["course"])
df["city_le"] = le.fit_transform(df["city"])

df

     user  course    city  course_le  city_le
0   Rohit  Python   Delhi          2        0
1  Ananya    Java  Mumbai          1        1
2  Suresh  Python   Delhi          2        0
3   Meena     C++    Pune          0        2
4   Kabir    Java  Mumbai          1        1