In [107]:
import pandas as pd
import numpy as np

In [108]:
df=pd.read_csv('/content/cars.csv')
df.sample(10)

        brand  km_driven    fuel                 owner  selling_price
5744  Hyundai      81000  Petrol  Fourth & Above Owner         200000
1220  Renault      25000  Petrol           First Owner         340000
915    Maruti     100000  Petrol           Third Owner         204999
3673     Tata      30000  Diesel           First Owner         250000
1747   Maruti      77000  Diesel          Second Owner         290000
3957  Hyundai      80000  Diesel          Second Owner         360000
5487  Hyundai      30000  Petrol           First Owner         470000
3811     Ford      70000  Petrol          Second Owner         500000
1569    Skoda      28182  Petrol           First Owner         675000
2642   Maruti      69779  Petrol           First Owner         600000

In [109]:
df['brand']

0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
8123    Hyundai
8124    Hyundai
8125     Maruti
8126       Tata
8127       Tata
Name: brand, Length: 8128, dtype: object

In [110]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [111]:
df['brand'].nunique()

32

In [112]:
df['owner']

0                First Owner
1               Second Owner
2                Third Owner
3                First Owner
4                First Owner
                ...
8123             First Owner
8124    Fourth & Above Owner
8125             First Owner
8126             First Owner
8127             First Owner
Name: owner, Length: 8128, dtype: object

In [113]:
df['fuel'].nunique()

4

##One Hot Encoding

In [114]:
#df=pd.get_dummies(df,columns=['fuel','owner'])

In [115]:
df.columns

Index(['brand', 'km_driven', 'fuel', 'owner', 'selling_price'], dtype='object')

##K-1 Hot Encoding

In [116]:
#df = pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)

## Using sklearn

In [117]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


X = df.iloc[:, 0:4]   # all rows, first 4 columns
y = df.iloc[:, 4]     # target column
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

X_train.head()

         brand  km_driven    fuel         owner
4561     Honda      40000  Diesel   First Owner
4045   Hyundai     120000     LPG   First Owner
1853    Nissan      80000  Petrol  Second Owner
3690      Ford      63000  Diesel   First Owner
1894  Mahindra     120000  Diesel   Third Owner

In [118]:
X_test.head()

         brand  km_driven    fuel         owner
3149      Tata      35000  Diesel   First Owner
1316    Maruti     150000  Petrol   Third Owner
7777   Hyundai      47000  Petrol  Second Owner
5223  Mahindra      90000  Diesel   First Owner
7049    Toyota     125000  Diesel   First Owner

In [119]:
ohe=OneHotEncoder(drop='first',dtype='int32')

In [120]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [121]:
X_test_new=ohe.transform(X_test[['fuel','owner']])

In [122]:

np.hstack((
    X_train[['brand', 'km_driven']].values,
    X_train_new
)).shape

(6502, 9)

##One hot encoding only on top categories

In [123]:
# Making threshold where value counts are more than 100

In [124]:
counts=df['brand'].value_counts()

In [125]:
df['brand'].unique()
threshold=100

In [126]:
counts[counts<=threshold].index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [127]:
pd.get_dummies(df['brand'].replace(counts[counts<=threshold].index,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3297,False,False,False,False,True,False,False,False,False,False,False,False,False
6500,False,False,False,True,False,False,False,False,False,False,False,False,False
3882,False,False,False,False,True,False,False,False,False,False,False,False,False
6657,False,False,False,False,False,False,False,False,False,False,True,False,False
7795,False,False,False,False,False,False,True,False,False,False,False,False,False